[workspace]

members = [
    "rs/client"
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Sotex Solutions"]
description = "The code for sotex box"
documentation = "https://sotex-lab.github.io/sotex-box/"
