services:
  backend:
    container_name: backend
    image: ghcr.io/sotex-lab/sotex-box/backend:${COMMIT_SHA}
    environment:
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    env_file:
      - .env

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.50.1
    volumes:
      - ./infra/config/prometheus:/etc/prometheus
      - prometheus:/prometheus
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=http://${DOMAIN_NAME}/prometheus/

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.4
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=${DOMAIN_NAME}
      - GF_SERVER_ROOT_URL=http://${DOMAIN_NAME}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=warn
    volumes:
      - ./infra/config/grafana/provisioning:/etc/grafana/provisioning
    command:
      - "sh"
      - "\"-c\""
      - "grafana-cli admin reset-admin-password ${GF_SECURITY_ADMIN_PASSWORD} && /run.sh"
    depends_on:
      - prometheus

  nginx:
    container_name: nginx
    image: nginx:1.25.4-alpine3.18
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - DOLLAR=$
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./infra/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/config/nginx/gateway.conf:/etc/nginx/gateway.conf.template
    command:
      - sh
      - -c
      - "envsubst < /etc/nginx/gateway.conf.template > /etc/nginx/apigateway.conf && cat /etc/nginx/apigateway.conf && nginx -g 'daemon off;'"
    depends_on:
      - grafana
      - prometheus
      - backend

volumes:
  prometheus:
