services:
  backend:
    container_name: backend
    image: ghcr.io/sotex-lab/sotex-box/backend:${COMMIT_SHA}
    ports:
      - 8080:8080

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.50.1
    volumes:
      - ./infra/config/prometheus:/etc/prometheus
      - prometheus:/prometheus
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.4
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./infra/config/grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  grafana:
  prometheus:
