services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.50.1
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.4
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
