site_name: Sotex Box docs
site_description: >-
  A collection of docs for the Sotex box

repo_name: Sotex Box
repo_url: https://github.com/sotex-lab/sotex-box/
edit_uri: edit/main/docs/

site_url: http://:/sotex-box/

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.code.copy
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/favicon.ico

plugins:
  - search
  - offline
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: sotex-lab/sotex-box
      branch: main

nav:
  - Introduction:
    - Project overview: index.md
    - System overview: introduction/system-overview.md
    - Hardware design: introduction/hardware-design.md
    - Software architecture: introduction/software-arch.md
    - Development process: introduction/development-process.md
    - Deployment: introduction/deployment.md
  - Repository:
    - Overview: repository/index.md
    - Working with repository: repository/working-with-repository.md
    - Dotnet:
      - Overview: repository/dotnet/index.md
    - Android:
      - Overview: repository/android/index.md
    - Infrastructure:
      - Overview: repository/infra/index.md
    - Continous Integration:
      - Overview: repository/CI/index.md
  - Observability:
    - Overview: observability/index.md
    - Custom metrics: observability/custom-metrics.md
  - Benchmarks:
    - EventCoordinator: 'benchmark-EventCoordinator.md'
  - Load test results:
    - Device connections: 'load-tests/load-test-results-connections.md'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - tables
