[project]
name = "sotex-box"
version = "0.1.0"
description = "Add a short description here"
authors = ["nikolamilosa <nikolamilosa20@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
mkdocs-git-committers-plugin-2 = ">=2.3.0,<2.4"
boto3 = ">=1.34.112,<1.35"
urllib3 = ">=2.2.1,<2.3"
mkdocs = ">=1.6.0,<1.7"
mkdocs-git-revision-date-localized-plugin = ">=1.2.5,<1.3"
flask = ">=3.0.3,<3.1"
mkdocs-material = ">=9.5.24,<9.6"
pipreqs = ">=0.4.13,<0.5"
