name: sotex-box
runtime: dotnet
description: Sotex-box deployment
config:
  aws:profile: service-account
  # Networking
  sotex-box:s3Url:
    description: Default S3 url
    default: https://s3.eu-central-1.amazonaws.com
    type: string
  sotex-box:sqsUrl:
    description: Default SQS url
    default: https://sqs.eu-central-1.amazonaws.com
    type: string
  sotex-box:networking-vpc-cidrBlock:
    description: VPC Cidr Block
    default: 10.0.0.0/16
    type: string
  sotex-box:networking-subnets-cidrBlock:
    description: Subnet cidrBlock blocks
    type: array
    items:
      type: string
    default:
      - 10.0.0.0/24
      - 10.0.1.0/24
  sotex-box:networking-subnets-availabilityZone:
    description: Subnet availability zones
    type: array
    items:
      type: string
    default:
      - eu-central-1a
      - eu-central-1b

  sotex-box:buckets:
    description: List of buckets to initialize
    type: array
    items:
      type: string
    default:
      - processed
      - non-processed
      - schedule

  sotex-box:sqsProcessorQueue:
    description: Queue for sqsProcessor job
    type: string
    default: sqsProcessor

  sotex-box:dbAllocatedStorage:
    description: Amount of storage in gigabytes
    type: integer
    default: 5
  sotex-box:dbEngine:
    description: Engine used for database
    type: string
    default: postgres
  sotex-box:dbEngineVersion:
    description: Engine version used for database
    type: string
    default: "16.2"
  sotex-box:dbInstanceClass:
    description: Instance class used for database machine
    type: string
    default: db.t3.micro

  sotex-box:ubuntuAmi:
    description: Ubuntu AMI used for running ec2 instance
    type: string
    default: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*

  sotex-box:publicKey:
    description: Public key used for signing in ec2
    type: string
    default: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8HeJ+7gg3jHS6b25feqENPpul4qBqwm07eS7oOxfuF

  sotex-box:ec2InstanceType:
    description: Instance type used to run ec2
    type: string
    default: t2.micro
