name: Build Pulumi IaC

on:
  pull_request:
    paths:
      - 'infra/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Lint the solution
      run: |
        dotnet tool restore
        dotnet dotnet-csharpier --check .

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1

    - name: Add profile credentials to ~/.aws/credentials
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile service-account
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile service-account

    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: sotex/sotex-box/staging
        comment-on-pr: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        work-dir: infra/backend
        upsert: true
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
