name: Dotnet pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "dotnet/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Lint the solution
      run: |
        dotnet format --verify-no-changes

    - name: Build the solution
      run: |
        dotnet build

    - name: Test the solution
      run: |
        make dotnet-tests
