name: Dotnet pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "dotnet/**"
      - "distribution/docker/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Lint the solution
      run: |
        dotnet tool restore
        dotnet dotnet-csharpier --check .

    - name: Build the solution
      run: |
        dotnet build

    - name: Test the solution
      run: |
        make dotnet-tests

    - name: Build the container for backend
      run: |
        make container-build-backend

    - name: Login to GitHub Container Registry
      # if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image to GitHub Container Registry
      # if: github.ref == 'refs/heads/main'
      run: |
        make container-push-backend
