name: Dotnet pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "android/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: "subosito/flutter-action@v2.12.0"
      with:
        flutter-version: '3.19.1'
        channel: 'stable'

    - name: Format Flutter
      run: dart format . --set-exit-if-changed -o json

    - name: Resolve Dependencies Launcher
      working-directory: "./android/launcher"
      run: flutter pub get

    - name: Resolve Dependencies Box
      working-directory: "./android/sotex_box"
      run: flutter pub get

    - name: Lint Flutter Launcher
      working-directory: "./android/launcher"
      run: flutter analyze --preamble --congratulate --fatal-warnings --fatal-infos

    - name: Lint Flutter Box
      working-directory: "./android/sotex_box"
      run: flutter analyze --preamble --congratulate --fatal-warnings --fatal-infos

    # - name: Build Flutter Launcher
    #   working-directory: "./android/launcher"
    #   run: flutter build apk

    # - name: Build Flutter Box
    #   working-directory: "./android/sotex_box"
    #   run: flutter build apk
