name: Dotnet pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "android/launcher/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: "subosito/flutter-action@v2.12.0"
      with:
        flutter-version: '3.19.1'
        channel: 'stable'

    - name: Check Formatting
      working-directory: "./android/launcher"
      run: dart format . --set-exit-if-changed -o json

    - name: Lint Flutter App
      working-directory: "./android/launcher"
      run: flutter analyze

    - name: Build Flutter App
      working-directory: "./android/launcher"
      run: flutter build apk
